import {
  ToCoreFromWebviewProtocol,
  ToWebviewFromCoreProtocol,
} from "./coreWebview.js";

// Message types to pass through from webview to core
// Note: If updating these values, make a corresponding update in
// extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt
export const WEBVIEW_TO_CORE_PASS_THROUGH: (keyof ToCoreFromWebviewProtocol)[] =
  [
    "ping",
    "abort",
    "history/list",
    "history/delete",
    "history/load",
    "history/save",
    "history/clear",
    "skills/list",
    "skills/curate",
    "sessions/search",
    "sessions/fork",
    "sessions/forkToWorktree",
    "worktrees/list",
    "worktrees/create",
    "worktrees/remove",
    "todos/list",
    "verify/recipe",
    "devdata/log",
    "config/addModel",
    "config/newPromptFile",
    "config/newAssistantFile",
    "config/ideSettingsUpdate",
    "config/addLocalWorkspaceBlock",
    "config/addGlobalRule",
    "config/deleteRule",
    "config/getSerializedProfileInfo",
    "config/deleteModel",
    "config/refreshProfiles",
    "config/openProfile",
    "config/updateSharedConfig",
    "config/updateSelectedModel",
    "mcp/reloadServer",
    "mcp/getPrompt",
    "mcp/startAuthentication",
    "mcp/removeAuthentication",
    "mcp/setServerEnabled",
    "context/getContextItems",
    "context/getSymbolsForFiles",
    "context/loadSubmenuItems",
    "context/addDocs",
    "context/removeDocs",
    "context/indexDocs",
    "autocomplete/complete",
    "autocomplete/cancel",
    "autocomplete/accept",
    "nextEdit/predict",
    "nextEdit/reject",
    "nextEdit/accept",
    "nextEdit/startChain",
    "nextEdit/deleteChain",
    "nextEdit/isChainAlive",
    "nextEdit/queue/getProcessedCount",
    "nextEdit/queue/dequeueProcessed",
    "nextEdit/queue/processOne",
    "nextEdit/queue/clear",
    "nextEdit/queue/abort",
    "llm/complete",
    "llm/streamChat",
    "llm/listModels",
    "llm/compileChat",
    "streamDiffLines",
    "chatDescriber/describe",
    "conversation/compact",
    "stats/getTokensPerDay",
    "stats/getTokensPerModel",
    "startTalk/connect",
    "startTalk/getConfigStatus",
    "startTalk/configure",
    "startTalk/sendAudio",
    "startTalk/sendText",
    "startTalk/startCapture",
    "startTalk/setMuted",
    "startTalk/setNotificationAnnouncements",
    "startTalk/getTranscript",
    "startTalk/delegateToMain",
    "startTalk/mainResult",
    "startTalk/endAudio",
    "startTalk/stop",
    "startTalk/sendToolResponse",
    "startTalk/startVideo",
    "startTalk/stopVideo",
    "startTalk/sendVideoFrame",
    "startTalk/listVideoSources",
    "startTalk/reportPlayback",
    "privacy/getPermissions",
    "privacy/setPermission",
    "privacy/resetPermissions",
    "goals/get",
    "goals/list",
    "goals/set",
    "goals/applyVerdict",
    "goals/clear",
    "github/getWorkItem",
    "scheduler/list",
    "scheduler/create",
    "scheduler/update",
    "scheduler/delete",
    "scheduler/runNow",
    "scheduler/claimDue",
    "scheduler/reportRun",
    // Codebase
    "index/setPaused",
    "index/forceReIndex",
    "index/indexingProgressBarInitialized",
    // Docs, etc.
    "indexing/reindex",
    "indexing/abort",
    "indexing/setPaused",
    "docs/initStatuses",
    "docs/getDetails",
    "docs/getIndexedPages",
    //
    "onboarding/complete",
    "addAutocompleteModel",
    "didChangeSelectedProfile",
    "tools/call",
    "tools/evaluatePolicy",
    "tools/preprocessArgs",
    "isItemTooBig",
    "process/markAsBackgrounded",
    "process/isBackgrounded",
    "process/killTerminalProcess",
    "models/fetch",
  ];

// Message types to pass through from core to webview
// Note: If updating these values, make a corresponding update in
// extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
export const CORE_TO_WEBVIEW_PASS_THROUGH: (keyof ToWebviewFromCoreProtocol)[] =
  [
    "configUpdate",
    "indexProgress", // Codebase
    "indexing/statusUpdate", // Docs, etc.
    "addContextItem",
    "refreshSubmenuItems",
    "isContinueInputFocused",
    "getWebviewHistoryLength",
    "getCurrentSessionId",
    "sessionUpdate",
    "didCloseFiles",
    "toolCallPartialOutput",
    "startTalk/event",
    "startTalk/runInMain",
    "startTalk/mainResultReady",
  ];
