import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { runtimeOpenApiDocument } from "../runtimeOpenApi.js";

const operations = Object.entries(runtimeOpenApiDocument.paths).flatMap(
  ([operationPath, pathItem]) =>
    Object.entries(pathItem).map(([method, operation]) => ({
      operationId: operation.operationId,
      method: method.toUpperCase(),
      path: operationPath,
    })),
);

const entries = operations
  .map(
    ({ operationId, method, path: operationPath }) =>
      `  ${JSON.stringify(operationId)}: { method: ${JSON.stringify(method)}, path: ${JSON.stringify(operationPath)} },`,
  )
  .join("\n");

const output = `// Generated by src/api/scripts/generateRuntimeApiClient.ts. Do not edit manually.\n\nexport const RUNTIME_API_OPERATIONS = {\n${entries}\n} as const;\n\nexport type RuntimeApiOperationId = keyof typeof RUNTIME_API_OPERATIONS;\n`;
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const target = path.resolve(
  scriptDir,
  "../generated/runtimeOperations.generated.ts",
);
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, output, "utf8");
console.log(`Generated ${operations.length} runtime API operations.`);
